language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew install opam
  - opam init
  - opam switch 4.04.0
  - eval `opam config env`
  - opam update
before_script:
  - opam pin add -y reason .
script: 
  - make test
  - git diff --exit-code
notifications:
  email:
    - yunxing@fb.com
    - reason@cloudwalk.me
